# Generated by Django 3.2.6 on 2021-12-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_expierence_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='expierence',
            name='para1',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='expierence',
            name='para2',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='expierence',
            name='para3',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
