# Generated by Django 3.2.6 on 2021-12-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211227_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecourse',
            name='homecourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.homecourse'),
        ),
    ]
