# Generated by Django 3.2.6 on 2022-01-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_remotecourse_homecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecourse',
            name='season',
        ),
        migrations.RemoveField(
            model_name='homecourse',
            name='year',
        ),
        migrations.RemoveField(
            model_name='remotecourse',
            name='department',
        ),
        migrations.RemoveField(
            model_name='remotecourse',
            name='season',
        ),
        migrations.RemoveField(
            model_name='remotecourse',
            name='year',
        ),
    ]
