# Generated by Django 3.2.6 on 2022-01-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220117_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemap',
            name='season',
            field=models.CharField(choices=[('S', 'Spring'), ('A', 'Autumn')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='coursemap',
            name='year',
            field=models.CharField(choices=[('2', 'Second year'), ('3', 'Third year'), ('4', 'Fourth year'), ('5', 'Dual Degree')], default='2', max_length=1),
        ),
    ]
