# Generated by Django 3.2.6 on 2022-01-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_coursemap_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemap',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AlterField(
            model_name='coursemap',
            name='University',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.university'),
        ),
    ]
